apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: friendzy-certificate
  namespace: friendzy
spec:
  dnsNames:
    - friendzy.shahabazsulthan.cloud
  secretName: friendzy-new-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
