apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-storage-class
provisioner: dobs.csi.digitalocean.com
parameters:
  fsType: ext4
  type: ssd
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true


